### PR TITLE
Make Fluency appender

### PR DESCRIPTION
**Pull request by takumakanari**
This p-r adds new appender, named FluencyLogbackAppender to send message to Fluentd with [Fluency](https://github.com/komamitsu/fluency) .

### CODE REVIEW

**Comment by sndyuk** [comment]
@takumakanari Could you add a sample configuration to [logback-appenders.xml](https://github.com/sndyuk/logback-more-appenders/blob/master/src/test/resources/logback-appenders.xml)? Thanks!

**Comment by takumakanari** [comment]
Hi @sndyuk, I added. Could you check it?

Thanks.

**Comment by sndyuk** [comment]
@takumakanari Thanks! version 1.4.1, including the changes, is going to be released today.

**Comment by takumakanari** [comment]
@sndyuk Very thanks for your review & merge my changes!

**Pull request merged**
